spring.application.name=resumenes

# Puerto del servidor local
server.port=8080

# =========================
# DATABASE (Railway)
# =========================
spring.datasource.url=jdbc:mysql://mainline.proxy.rlwy.net:20755/railway?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=zCdomaITqeVQudofdPYqiBSxlJlVNKtC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# JWT
# =========================
app.jwt.secret=7d3bX9!a2LzR#vCqP8tFnZ4g$kT6mBhW1eY@pQjUv0sNlXEfM5GwAiCZ
app.jwt.expiration=3600000


# =========================
# Stripe
# =========================
stripe.secret.key=sk_test_51P2wD0BQP2FXIWh86Keyc3juzu2rahc8wos3nQtbH0zukfoJU4RkfMnnUleRgm6x8pcEKGGuHowgb4XglQQCYng800xokcISCR
stripe.webhook.secret=whsec_16bb96524895398a29843d065ad27283d57d9cb45435729b75b0b772db3cfd11
stripe.success.url=http://localhost:5173
stripe.cancel.url=http://localhost:5173


# =========================
# Doc
# =========================
springdoc.swagger-ui.path=/documentacion
springdoc.api-docs.path=/openapi

