spring.application.name=resumenes

# Puerto del servidor local
server.port=8080


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# DATABASE
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================
# JWT
# =========================
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=${APP_JWT_EXPIRATION:3600000}  # Default opcional

# =========================
# Stripe
# =========================
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
stripe.success.url=${STRIPE_SUCCESS_URL:http://localhost:5173}
stripe.cancel.url=${STRIPE_CANCEL_URL:http://localhost:5173}



# =========================
# Doc
# =========================
springdoc.swagger-ui.path=/documentacion
springdoc.api-docs.path=/openapi

